openapi: 3.2.0
info:
  description: 'Terms & Conditions


    All details on this document are copyrighted and are protected by Egencia copyright laws.'
  title: BI Custom Data Field Cleanup Controller API
  version: v1.0
servers:
- url: https://apis.egencia.com/bi/api
  description: Generated server url
tags:
- name: custom-data-field-cleanup-controller
paths:
  /v1/sensitive/audit/clean:
    post:
      operationId: cleanup
      parameters:
      - in: query
        name: year
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      tags:
      - custom-data-field-cleanup-controller
      summary: Cleanup
      x-summary-source: derived
components:
  securitySchemes:
    OAuth2:
      flows:
        clientCredentials:
          tokenUrl: https://apis.egencia.com/auth/v1/token
      type: oauth2
